### ISSUE TITLE
Resource path

### ISSUE THREAD

**Issue by rahmanQaiser** [duyphan2502/LaraWebEd#6]
I just did same as per your config for virtual host.
But the Problem is with relative path for resources.
What i am getting in console is
http://rahman.projects.dev/admin/theme/images/logo.png 404 (Not Found)
http://rahman.projects.dev/admin/theme/images/logo.png 404 (Not Found)
...
...

instead the relative path should be
http://rahman.projects.dev/LaraWeb/admin/theme/images/logo.png
Basically what i am missing document root so, how to solve this?

**Comment by duyphan2502** [comment]
We cannot use folder path. Why don't you point your document root to public folder?

**Comment by rahmanQaiser** [comment]
how do i point it?

**Comment by duyphan2502** [comment]
For example:

<VirtualHost *:80>
  ServerName tedozicms.mydev.local
  DocumentRoot "D:\Projects\repos\mine\tedozi-cms\public"
  <Directory "D:\Projects\repos\mine\tedozi-cms\public">
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
